### ISSUE TITLE
How to select a link using hints and send it to shell command?

### ISSUE THREAD

**Issue by whereistejas** [pentadactyl/pentadactyl#12]
I want to set up a keybinding to download youtube videos using `youtube-dl`.

**Comment by jackrosenthal** [comment]
I will leave this for someone to implement if they would like to. Pull requests very much appreciated!

**Comment by whereistejas** [comment]
> I will leave this for someone to implement if they would like to. Pull requests very much appreciated!

Are you saying this feature doesn't exist ?

**Comment by jackrosenthal** [comment]
You probably can accomplish it with a pretty simple JavaScript extension. If you do, please feel free to share in the contrib directory.

**Comment by resolritter** [comment]
You can execute arbitrary commands with `io.system`.

For actually getting the attribute of the thing you targetted in **Hint mode**, you'll need to add a new custom mode to **Hint mode**, like it's done in

./pentadactyl/common/content/hints.js#L788

**(warning: code not tested) something like this**

    autocmd Enter * <<EOF
        config.modules.hints.addMode("Z", "Download from Youtube", elem => io.system(["youtube-dl", elem.href]))
    EOF

Unsure if it'd block your browser or not. Also unsure if you can execute in "shell" mode asynchronously and get some kind of message later.

**Comment by jackrosenthal** [comment]
@whereistejas: can you reopen this issue if @reaysawa's suggestion does not provide what you need?

**Comment by whereistejas** [comment]
@jackrosenthal I tried to use that command, it *didn't work*. I tried adding the command to the hint.js file and compile the code. That ended up showing the command, but it produced no output.

@jackrosenthal @reaysawa we can refer to this [rc file](https://github.com/azuwis/.pentadactyl/blob/master/rc#L199-L215)
It seems like `io.run()` is the method we are looking for.

**Comment by whereistejas** [comment]
@jackrosenthal @reaysawa we can refer to this [rc file](https://github.com/azuwis/.pentadactyl/blob/master/rc#L199-L215)
It seems like `io.run()` is the method we are looking for.

**Comment by whereistejas** [comment]
`this.addMode("X", "Download YouTube Videos", loc => io.system('youtube-dl \"' + loc + '\"'));`
This solution worked like a charm! How ever, I am a bit confused. Why is a hints-mode binding in itself, another mode? That doesn't make sense to me. Can someone please enlighten me?

**Comment by whereistejas** [comment]
Also, @jackrosenthal I have submitted a PR, where-in I have added that command to the `hint.js` file. So, can we say that the feature request is complete?

**Comment by resolritter** [comment]
@whereistejas from my understanding, hinting is known as the aspect of targetting elements (you can think in terms of the overlay itself and the logic for filtering targets).

When you add a "hint mode" you're giving purpose to the action of hinting; hints aren't perceived as mode in itself because the same idea is given a different purpose (copy text, open in tab, open in another window, etx...) depending on the mode you choose. I'm not the creator of the library but that's how I understand this paradigm.
