### ISSUE TITLE
palemoon hangs after dragging the window on other screen/screen connect

### ISSUE THREAD

**Issue by pizdjuk** [pentadactyl/pentadactyl#13]
I suspect, that the problem is in changing the resolution.
The behavior is follows:

start palemoon, connect other monitor, drag the palemoon onto other monitor.

the palemoon seems not to respond. For example: typing :open google.com dont result in anything. But after this, if one press on maximaze button on the palemoon's window the typed text appears.

Seems that palemoon receives the keyboard and process it correctly, but doesn't display till the window size changes.

I hope this description helps to fix this annoying bug.

See some discussion [here](https://github.com/MoonchildProductions/UXP/issues/990)

**Comment by jackrosenthal** [comment]
What window manager are you using? This may help me try to replicate.

**Comment by pizdjuk** [comment]
I'm using MATE with marco

**Comment by pizdjuk** [comment]
BTW, palemoon seems to hang without dragging too. Only connect the monitor suffices.

**Comment by pizdjuk** [comment]
any news?

**Comment by jackrosenthal** [comment]
Tested and unable to reproduce using Pentadactyl 1.3.1, PaleMoon 28.7.1, MATE 1.22.2 and marco 1.22.3
