### ISSUE TITLE
mention the #pentadactyl IRC channel in the readme

### ISSUE THREAD

**Issue by whereistejas** [pentadactyl/pentadactyl#14]
There is an official pentadactyl channel on the OFTC network. It has been dead and quiet for a while. Mentioning the channel in the README.md may help it get some traction and attention.

**Comment by jackrosenthal** [comment]
I don't think Pentadactyl has the userbase anymore to practically keep up a lively IRC channel. 🙁

For me personally, it's probably easiest to just keep using the GitHub issues site for bugs/feature requests/user support. So if an IRC channel were to be created/started to be used again, someone else than myself would have to be responsible for monitoring it.

**Comment by whereistejas** [comment]
If you don't mind, I can take that responsibility. I'm always online on IRC and I know the basics of penta well enough. I don't any scripting though.

**Comment by jackrosenthal** [comment]
Awesome! Can you submit a PR with the IRC details?

**Comment by whereistejas** [comment]
Sure. No issues. :)

**Comment by RFDAJE** [comment]
no pr so far, considered as outdated.
