### ISSUE TITLE
help page links do not work and needs update

### ISSUE THREAD

**Issue by UddipakBhuyan** [pentadactyl/pentadactyl#20]
The help page opened using 

> :help
 
or after installing the plugin for the first time has links that do not work. The only way to access the documentation is using 

> :helpall

**Comment by dther** [comment]
Can confirm this is still the case as of time of writing.

**Comment by genebustam** [comment]
This happens to me as well.

**Comment by Studiedlist** [comment]
Still not fixed

**Comment by RFDAJE** [comment]
this cannot be reproduced with Pale Moon v29
