### ISSUE TITLE
Error on keyboard cursors

### ISSUE THREAD

**Issue by bladane** [pentadactyl/pentadactyl#21]
I am using Pentadactyl 1.3.1 installed yesterday on Pale Moon 28.7.2 64 bits (Win 10 OS x64).
When add-on is enabled and after start of Pale Moon, on first tab I open some web page (:open duckduckgo and go to another page that has content to be scrolled down) and try to use navigation keys (j, k, C-F,...) I am getting following error:
`resource://dactyl/buffer.jsm: 1740: TypeError: overlay.activeModules.options is undefined`

In some cases, it stars working after I open new tab with another site but not all the time.

**Comment by RFDAJE** [comment]
close due to outdated bug report for Pale Moon v28
