### ISSUE TITLE
Change to letters instead of numbers for links?

### ISSUE THREAD

**Issue by so9q** [pentadactyl/pentadactyl#22]
Hi
I got used to Vim mode using chrome for some time. It has letters which are nicer than having numbers like pendactyl for links because the numbers are quite far away form the home row.

Is it possible to tweak pendactyl into using letters instead of numbers for links?

**Comment by xaizek** [comment]
There is `'hintkeys'` option, mine is set this way in `~/.pentadactylrc`:
```
set hintkeys=ghfjdksla;
```

**Comment by so9q** [comment]
Big thanks! Pentadactyl is awesome :)
