### ISSUE TITLE
Page Up/Page Down keyboard shortcuts

### ISSUE THREAD

**Issue by smnthermes** [pentadactyl/pentadactyl#25]
The shortcuts for the Page Up/Page Down keys don't work when using Pentadactyl.

**Comment by jackrosenthal** [comment]
Have you tried `Ctrl-F` and `Ctrl-B`?

**Comment by smnthermes** [comment]
They don't work as well, the same error messaged is shown for both shortcut sets:
`resource://dactyl/buffer.jsm: 1740: TypeError: overlay.activeModules.options is undefined`

**Comment by morphors** [comment]
I had the same problem here after the last update. It worked after going to Preferences> Advanced> Scrolling and deselecting "Use smooth scrolling" and then Ok

scrolling shortcuts are back up and running

After that, I can return that option.

**Comment by RFDAJE** [comment]
this issue cannot be reproduced on Pale Moon 29.1.1, consider as invalid.
