### ISSUE TITLE
Media Playback Buttons Not Working with Hints

### ISSUE THREAD

**Issue by fohrums** [pentadactyl/pentadactyl#30]
Pentadactyl Hints is used to open hyperlinks on webpages. Problem is there are some play/pause buttons on media sites that don't cooperate with pentadactyl's `Hints (or f-key)`.

I would like to know if anybody has experienced hints not working for sites like [www.bandcamp.com](url)?

If this is an outside issue, then is there a way to control the mouse-position-focus so I can interact with media playback buttons in that fashion?

**Comment by RFDAJE** [comment]
this belongs to user setting, e.g. https://daily.bandcamp.com/lists/juggaknots-discography-guide you can append playback element `icon,div[class=icon]` like `:set hinttags=:-moz-any-link,area ..., icon,div[class=icon]`.
