### ISSUE TITLE
No release with Pale Moon 29.* Support

### ISSUE THREAD

**Issue by albertdev** [pentadactyl/pentadactyl#33]
I just got the Pale Moon 29.0.0 update and it marks Pentadactyl 1.3.1 as incompatible.

The problem appears to be fixed in the `master` branch in commit 9d40dc0818e3a9ccb429de4f787f538c93fb9786 but this hasn't been included in a release just yet.

Many thanks for your efforts over the past years!

**Comment by thegala** [comment]
Until there is new release u can use my local build.
[penta.zip](https://github.com/pentadactyl/pentadactyl/files/5914812/penta.zip)

**Comment by pink-mist** [comment]
I also just got Pale Moon 29.0.0 and had to build from master to get pentadactyl back in working order.

**Comment by weiss-d** [comment]
I'm typing this in Firefox because of that 😭

**Comment by RFDAJE** [comment]
it's time for a new release version 1.4 :-D

**Comment by jackrosenthal** [comment]
Hi all,

I've finally given up on using Pale Moon for my web browsing purposes... anyone here interested in taking over mantainer of this project? I'll give you owner on the repo and see if the palemoon addons page can be transfered?

**Comment by RFDAJE** [comment]
@jackrosenthal I would like to take over the post.

**Comment by jackrosenthal** [comment]
RFDAJE: I sent you an invite to owership of the github org.

Do you have an account on Phoebus (addons.palemoon.org)? I'm certain there's someone we can ask to help transfer ownership of the extension on there.

**Comment by mattatobin** [comment]
I can do it manually. Not a problem but it does mean you will loose access to it.

**Comment by jackrosenthal** [comment]
Yep, I'm ready to loose access to it :)

Thanks for the fun times, pentadactyl.

**Comment by mattatobin** [comment]
Well Google will do that to you. Anyway, transfer complete.

Do note, @jackrosenthal, your account may be purged in the future for having no assigned add-ons as per our semi-regular clean up of accounts that sign up for no reason and never submit anything. You will simply be eventually caught in the round up.

**Comment by RFDAJE** [comment]
thanks @jackrosenthal @mattatobin 

ps. maintainer transfer request post https://forum.palemoon.org/viewtopic.php?f=46&t=26627
