### ISSUE TITLE
Bind key to spawning system process

### ISSUE THREAD

**Issue by dblsaiko** [pentadactyl/pentadactyl#35]
I'd like to bind a key to spawning mpv with the current URL to play youtube videos (and bind other commands like sharing URLs via kdeconnect-cli, but same thing), like `:bind ,m spawn mpv {url}` for qutebrowser. Is this possible?

**Comment by RFDAJE** [comment]
try `map ,m :execute "!mpv " + content.location<CR>`

**Comment by dblsaiko** [comment]
Thanks!
