### ISSUE TITLE
Javascript depreciation warnings

### ISSUE THREAD

**Issue by albertdev** [pentadactyl/pentadactyl#4]
When running the addon I sometimes get an indication of an error in my statusline.

When I run `:messages` this is the result:

> resource://dactyl/base.jsm:2044: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl/base.jsm:2029: toArray is deprecated: Please use Array.from instead.
resource://dactyl-content/modes.js:312: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl/template.jsm:178: Ary#iterValues is deprecated: Please use Array#values instead.
resource://dactyl-content/mappings.js:318: Ary#iterValues is deprecated: Please use Array#values instead.

Encountered with Pale Moon 28.4.2 and 28.5.2.

**Comment by jackrosenthal** [comment]
Thanks for the report
