### ISSUE TITLE
Update? Not compatible

### ISSUE THREAD

**Issue by rcrx** [pentadactyl/pentadactyl#41]
Error: "Not compatible with Palemoon 31.1.1

**Comment by jackrosenthal** [comment]
I think @RFDAJE is the current maintainer

**Comment by RFDAJE** [comment]
I do not actively using palemoon anymore, anyone interest to be the new maintainer?

**Comment by usrlocalben** [comment]
_master_ branch works-for-me in 31.1.1

**Comment by rcrx** [comment]
Okay, master branch is working. Installing from the extension center at addons.palemoon.org/extensions is not working; cloning 1.4 and installing from file is working.
