### ISSUE TITLE
Unable to scroll page when addon is installed

### ISSUE THREAD

**Issue by albertdev** [pentadactyl/pentadactyl#5]
I was running the old version at https://github.com/madand/pentadactyl-pm up till today.

Upgraded to Pale Moon 28.5.2 and installed Pentadactyl 1.3.0 from [addons.palemoon.org](https://addons.palemoon.org/addon/pentadactyl-community/). Running Windows 10 Home edition, updated to version 1903.

Now when I go to any page the page is stuck to the top, it's impossible to scroll down using space, HJKL or the arrow keys. I even tried grabbing the scrollbar's thumb using the mouse, but dragging it down does nothing unless you drag it down fast, and even then you can see it glitch to wherever you dragged it just before it snaps back to the top.

I must admit that I have quite a few custom mappings in my `.pentadactylrc`, but I actually renamed the rc file and after restarting PaleMoon there is no difference. I have disabled all my other extensions for a while but it seems to make no difference either.

**Comment by jackrosenthal** [comment]
Thanks for the report. I don't have easy access to Windows, but I will try and see if I can set up a VM to test this in.

**Comment by thegala** [comment]
I have same problem on Linux. I don't have any addons installed and i tried with fresh PaleMoon user profile. Also this problem persist in PaleMoon version 28.6.0. Even tried with empty pentadactyl config. No luck.

**Comment by thegala** [comment]
Reverting this commit [783a2c5](https://github.com/pentadactyl/pentadactyl/commit/783a2c5ce0ec4529376cb3f28707d833245fa478)  fixed my problem.

**Comment by john-x** [comment]
Also using Linux with the same problem. I'm able to scroll normally using the mouse wheel but as soon as I use any of the scroll buttons the page stays locked to the top until I reload it. I opened the Browser Console and this is the error that appears when this happens: 
```
can't access dead object  
buffer.jsm:1765
	next resource://dactyl/buffer.jsm:1765:21
	timeout_notify resource://dactyl/base.jsm:1134:17
	next@resource://dactyl/buffer.jsm:1765:21
	timeout_notify@resource://dactyl/base.jsm:1134:17
```

**Comment by john-x** [comment]
Disabling smooth scrolling with ':set scrollsteps=1' seems to fix it.

**Comment by john-x** [comment]
Disabling smooth scrolling with `:set scrollsteps=1` seems to fix it.

**Comment by thegala** [comment]
Changing this line fixed my problem.
```
diff --git a/common/modules/buffer.jsm b/common/modules/buffer.jsm
index a8895a7c..30b6b662 100644
--- a/common/modules/buffer.jsm
+++ b/common/modules/buffer.jsm
@@ -1737,8 +1737,8 @@ var Buffer = Module("Buffer", {
         let timers = new WeakMap;
 
         return function smoothScrollTo(node, x, y) {
-            let time = overlay.activeModules["scrolltime"];
-            let steps = overlay.activeModules["scrollsteps"];
+            let time = overlay.activeModules.options["scrolltime"];
+            let steps = overlay.activeModules.options["scrollsteps"];
 
             let elem = Buffer.Scrollable(node);
```

**Comment by albertdev** [comment]
@thegala Thanks, the extension allows scrolling again and at least allows me to use it on PaleMoon 28.4.1 and 28.6.0.1 (the newest).

However, that patch did introduce the following error at startup in PM 28.4.1:

```
resource://dactyl/buffer.jsm: 1740: TypeError: overlay.activeModules.options is undefined
resource://dactyl/buffer.jsm: 1740: TypeError: overlay.activeModules.options is undefined
```

EDIT: It's not just after starting, it seems to happen the first time you scroll after PM has been started, and that also happens on PM 28.6.0.1.
