### ISSUE TITLE
Palemoon 28.6 support

### ISSUE THREAD

**Issue by lichray** [pentadactyl/pentadactyl#6]
![image](https://user-images.githubusercontent.com/433009/60562827-c61ed580-9d1e-11e9-8264-7c60acc75c91.png)

Unable to find any commands in last-line mode.

**Comment by RFDAJE** [comment]
I've made some quick fixes in my fork, it's not perfect but at least it is again usable with palemoon-28.6.

https://github.com/RFDAJE/pentadactyl

**Comment by TimB87** [comment]
This works for me, but typed hint numbers are not displayed anymore.

**Comment by RFDAJE** [comment]
> This works for me, but typed hint numbers are not displayed anymore.

what do you mean by "typed hint numbers"? hit "f" links will be hinted, then type "12", a "12" hinted link will be opened, this works for me.

**Comment by TimB87** [comment]
Sorry for not being clear enough. When you hit f, the status bar changes to "follow hint: " and you are able to type in the hint number (if the default settings aren't changed, at least). This input is not shown anymore? Maybe I'm wrong :smiley: 
Following hints works though, like you said! :+1:

**Comment by RFDAJE** [comment]
you mean, on the status bar not getting what typed, right? if it is not so before 28.6 update, then this is new bug, since the status bar is hidden with my preference, I don't know what is the previous behavior.

**Comment by TimB87** [comment]
I am not 100% sure about this (if it's a new bug), since I am rather new to use pentadactyl.. so maybe someone else can answer that one? I would just suspect it would show what you typed before?

Other than that, it runs all fine for me!

**Comment by xaizek** [comment]
Follow hint on the status bar isn't displayed on 28.5.2, so it's not due to 28.6 update.

**Comment by lil-schemer** [comment]
@RFDAJE The fix works but now I have this issue #5

**Comment by jackrosenthal** [comment]
@RFDAJE think things are getting ready to pull? Can you submit a PR?

**Comment by jackrosenthal** [comment]
Thanks everyone for your reports and patches. I think 28.6 is working great on master branch of git repo, and I'll make a 1.3.1 release soon. Please let me know if I missed anything.
